[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["autotest1689054614058"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "autotest1689054614058"
  org = "uvindradiasjayasinha"
  version = "3.1.1"

